common:
  docker-rust: &docker-rust
    docker:
      image: "rust:1.94"
      mount-buildkite-agent: true

steps:
  - label: "Lint server"
    commands:
      - . .buildkite/install-server-dependencies.sh
      - rustup component add clippy
      - rm -r .cargo # Remove the cargo config to prevent it from trying to build std (only needed for 3DS builds)
      - cargo clippy -p n3ds-remote-play-server
    plugins:
      - *docker-rust

  - label: "Lint client"
    commands:
      - . .buildkite/install-3ds-tools.sh
      - rustup component add clippy
      - cargo 3ds clippy -p n3ds-remote-play-client
    plugins:
      - *docker-rust

  - label: "Test (common package)"
    commands:
      - rm -r .cargo # Remove the cargo config to prevent it from trying to build std (only needed for 3DS builds)
      - cargo test -p n3ds-remote-play-common
    plugins:
      - *docker-rust

  - label: "Build (server)"
    commands:
      - ./.buildkite/install-server-dependencies.sh
      - rm -r .cargo # Remove the cargo config to prevent it from trying to build std (only needed for 3DS builds)
      - cargo build -p n3ds-remote-play-server --release
    artifact_paths: "target/release/n3ds-remote-play-server*"
    plugins:
      - *docker-rust

  - label: "Build (client)"
    commands:
      - . .buildkite/install-3ds-tools.sh
      - cargo 3ds build -p n3ds-remote-play-client --release
    artifact_paths: "target/armv6k-nintendo-3ds/release/n3ds-remote-play-client*"
    plugins:
      - *docker-rust